# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cybervein.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cybervein.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0ecybervein.proto\"\x1f\n\x0b\x41uthRequest\x12\x10\n\x08Password\x18\x01 \x01(\t\"\x16\n\x05Token\x12\r\n\x05token\x18\x01 \x01(\t\"\x1d\n\x0e\x43ommandRequest\x12\x0b\n\x03\x43md\x18\x01 \x01(\t\";\n\x1bQueryPrivateWithAddrRequest\x12\x0b\n\x03\x43md\x18\x01 \x01(\t\x12\x0f\n\x07\x41\x64\x64ress\x18\x02 \x01(\t\"\x1f\n\rQueryResponse\x12\x0e\n\x06Result\x18\x01 \x01(\t\"\x8b\x01\n\x0f\x45xecuteResponse\x12\x0b\n\x03\x43md\x18\x01 \x01(\t\x12\x15\n\rExecuteResult\x18\x02 \x01(\t\x12\x11\n\tSignature\x18\x03 \x01(\t\x12\x10\n\x08Sequence\x18\x04 \x01(\t\x12\x11\n\tTimeStamp\x18\x05 \x01(\t\x12\x0c\n\x04Hash\x18\x06 \x01(\t\x12\x0e\n\x06Height\x18\x07 \x01(\x03\"i\n\x14\x45xecuteAsyncResponse\x12\x0b\n\x03\x43md\x18\x01 \x01(\t\x12\x11\n\tSignature\x18\x02 \x01(\t\x12\x10\n\x08Sequence\x18\x03 \x01(\t\x12\x11\n\tTimeStamp\x18\x04 \x01(\t\x12\x0c\n\x04Hash\x18\x05 \x01(\t2\xf6\x02\n\x08cybervein\x12\x1c\n\x04\x41uth\x12\x0c.AuthRequest\x1a\x06.Token\x12(\n\x05Query\x12\x0f.CommandRequest\x1a\x0e.QueryResponse\x12\x33\n\x10QueryPrivateData\x12\x0f.CommandRequest\x1a\x0e.QueryResponse\x12K\n\x1bQueryPrivateDataWithAddress\x12\x1c.QueryPrivateWithAddrRequest\x1a\x0e.QueryResponse\x12,\n\x07\x45xecute\x12\x0f.CommandRequest\x1a\x10.ExecuteResponse\x12\x36\n\x0c\x45xecuteAsync\x12\x0f.CommandRequest\x1a\x15.ExecuteAsyncResponse\x12:\n\x15\x45xecuteWithPrivateKey\x12\x0f.CommandRequest\x1a\x10.ExecuteResponseb\x06proto3'
)




_AUTHREQUEST = _descriptor.Descriptor(
  name='AuthRequest',
  full_name='AuthRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Password', full_name='AuthRequest.Password', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=49,
)


_TOKEN = _descriptor.Descriptor(
  name='Token',
  full_name='Token',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='Token.token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=73,
)


_COMMANDREQUEST = _descriptor.Descriptor(
  name='CommandRequest',
  full_name='CommandRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Cmd', full_name='CommandRequest.Cmd', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=104,
)


